### ISSUE TITLE
CD step should be implemented

### ISSUE THREAD

**Issue by Whitesheep18** [AndersStendevad/DevOpsData#14]
Anders started on it already

**Comment by edibegovic** [comment]
In the final working-version, maybe we should only have auto-deployments on releases :)

**Comment by edibegovic** [comment]
We use this approach (from @gergokoncz)

https://medium.com/swlh/how-to-deploy-your-application-to-digital-ocean-using-github-actions-and-save-up-on-ci-cd-costs-74b7315facc2

**Comment by AndersStendevad** [comment]
Done
