### ISSUE TITLE
Fix API test: use Django TestCase

### ISSUE THREAD

**Issue by edibegovic** [AndersStendevad/DevOpsData#15]
Use Djanggo Test Suit for API tests instead of Python unit-test. This creates a temporary database for the tests instead of using the "production", thus not preserving state.

**Comment by AndersStendevad** [comment]
We can also make a new service in the docker-compose without a volume, so it will never preserve state. Look at api_test and web_test

**Comment by HogniJacobsen** [comment]
Fixed 🥳

**Comment by edibegovic** [comment]
Tests fixed 🥳
